### ISSUE TITLE
Renaming the repo to "ChatRunner" instead of "Game"

### ISSUE THREAD

**Issue by brytorres** [ChatRunner/Game#3]
I think we should change the repo name to ChatRunner to avoid confusion on the teams local environments, and anyone else who decides to join in from now.

We would have to delete and relink our local clones to the new clone to avoid confusion with the new name and Git.

**Comment by Richard87** [comment]
Yeah, that makes a lot of sense! I will update it when I get back to my
office!

Richard

**Comment by Richard87** [comment]
Done!
